/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT, 
    name VARCHAR(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BIT, 
    weight DECIMAL,
);

CREATE TABLE owners (
  	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   	full_name VARCHAR(100),
   	age INT
);

CREATE TABLE species (
  	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   	name VARCHAR(100)
);
CREATE TABLE vets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    date_of_graduatation DATE
);

CREATE TABLE specializations (
	species_id INT REFERENCES species (id),
	vet_id INT REFERENCES vets (id)
);

CREATE TABLE visits (
	animal_id INT REFERENCES animals (id),
	vet_id INT REFERENCES vets (id),
	date_of_visit DATE
);

ALTER TABLE animals ADD species VARCHAR(100);
ALTER TABLE animals ALTER COLUMN id SET NOT NULL;
ALTER TABLE animals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE animals ADD CONSTRAINT animals_pk PRIMARY KEY (id);
ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals ADD species_id INT REFERENCES species(id);
ALTER TABLE animals ADD owner_id INT REFERENCES owners(id);