/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT, 
    name VARCHAR(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BIT, 
    weight DECIMAL,
);

ALTER TABLE animals ADD species VARCHAR(100);

CREATE TABLE owners (
  	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   	full_name VARCHAR(100),
   	age INT
);

CREATE TABLE species (
  	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   	name VARCHAR(100)
);
