/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT, 
    name VARCHAR(100),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BIT, 
    weight DECIMAL,
);

ALTER TABLE animals ADD species VARCHAR(100);

CREATE TABLE owners (
  	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   	full_name VARCHAR(100),
   	age INT
);

CREATE TABLE species (
  	id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   	name VARCHAR(100)
);

ALTER TABLE animals ALTER COLUMN id SET NOT NULL;
ALTER TABLE animals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE animals ADD CONSTRAINT animals_pk PRIMARY KEY (id);
ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals ADD species_id int REFERENCES species(id);
ALTER TABLE animals ADD owner_id int REFERENCES owners(id);